version: '3.8'

services:
  web:
    build: .
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
